---
title: Transactional注解与try{}catch(Exception e){}同时使用事务控制无效问题
date: 2023-02-16 09:37:39
permalink: /javaCategory/13/
categories:
  - 后端
  - java
tags:
  - 
author: 
  name: ~chao
  link: https://github.com/chaos1973/chaos_front
---
# @Transactional注解与try{}catch(Exception e){}同时使用事务控制无效问题

原文链接：[https://blog.csdn.net/moke\_ant/article/details/104994442](https://blog.csdn.net/moke_ant/article/details/104994442)

1.@Transactional的使用  
通常我们使用注解事务是配置文件开启注解驱动，在相关的类或是方法上通过@Transaction注解的方式使用事务。  
2.@Transactional 使用注意点  
注解只有在抛出RuntimeException 或者是Erroe时从才会触发事务的回滚，常见的非RuntimeException是不会触发事务的回滚的。  
但是我们平时做业务处理时，需要捕获异常，即在方法中使用try{}catch(Exception e){},此时在方法上在使用@Transactional注解， 方法出现异常也不会进行回滚。  
同理 在其他文章或是解答中有建议使用@Transactional(rollbackFor = Exception.class) 进行事务的回滚，亲测此方法也是不行的，如果你的方法中有使用到了其他异常或是自定义的异常，同样事务也是不会回滚的。  
最后的解决方法是在catch中进行手动的事务回滚。具体案例如下代码  
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200320172403321.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L21va2VfYW50,size_16,color_FFFFFF,t_70)  
本人的理解是 在方法中已经进行try catch 即捕获异常并且把异常进行处理了。异常的生命周期已经结束，而并没有将异常抛出所以@Transtaction 注解并没有能监听到异常 所以 注解没哟起到事务回滚的作用